{{- if and .Values.mongodb.enabled .Values.mongodb.auth.enabled (not .Values.mongodb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentpep.fullname" . }}-mongodb
  labels:
    {{- include "agentpep.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.mongodb.auth.rootUsername | b64enc | quote }}
  password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
{{- end }}
